# Generated by Django 5.1.1 on 2024-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha',
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
