# Generated by Django 5.1.1 on 2024-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paciente_email_alter_paciente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('clinico', 'Clínico'), ('pediatria', 'Pediatría'), ('traumatologia', 'Traumatología'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología')], max_length=20),
        ),
    ]
