# Generated by Django 5.1.1 on 2024-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
