# Generated by Django 5.1.1 on 2024-11-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paciente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medico',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
